openapi: 3.0.0
info:
  title: medcare
  version: '1.0'
  contact:
    name: Akbar
    email: akbartukhtamurotov@gmail.com
  description: Medcare API
paths:
  '/regions/{id}':
    get:
      summary: Get region
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  stuff:
                    type: string
                  value:
                    type: string
      description: Great endpoint does a load of stuff
      operationId: ''
servers:
  - url: 'http://89.200.100.102/api/v1'
    description: dev
